logo: /assets/img/logo.png
theme: jekyll-theme-minimal
page_title: Ocado Technology
title: Ocado Technology Sofia
favicon: /assets/img/favicon.png
description: Emerging Talents '24 - Advanced Technology